services:
  - type: web
    name: macro-max-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /v1/healthcheck
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        value: disabled
